---
- name: 'Variable Introduction'
  hosts: all
  become: yes
  gather_facts: no
  vars:
    filepath: /tmp/variableintro.txt

  tasks:
   - name: 'Creating File.'
     file:
      path: "{{filepath}}"
      state: touch

   - name: 'Printing the value of variable -filepath- using debug module'
     debug:
      var: filepath
