---
- name: 'Variable Introduction'
  hosts: all

  tasks:
   - name: 'Creating File.'
     copy:
       content: 'dummy content'
       dest: /tmp/dummy.txt
     register: file_status     


   - name: 'debugging the output of -cahnged- from -file_status- variable'
     debug:
      var: file_status.changed
