---
- hosts: amazon
  become: yes
  tasks:
   - name: Install Httpd And Php Modules
     yum:
       name:
         - httpd
         - php
         - php-mbstring
         - php-soap
         - php-mysql
         - php-gd
       state: present
     register: httpdStatus

   - debug:
      var: httpdStatus


   - name: Creating PhP Website.
     copy:
       content: '<?php phpinfo(); ?>'
       dest: /var/www/html/index.php
     register: contentStatus

   - name: Restart/Enabling Httpd
     service:
       name: httpd
       state: restarted
       enabled: yes
     when: httpdStatus.changed  or  contentStatus.changed
