---
- name: 'Virtualhost - Creating From Jinja Template.'
  template:
    src: virtualhost.j2
    dest: '/etc/httpd/conf.d/{{domain}}.conf'
      
- name: 'Virtualhost - creating Document-Root.'
  file:
    path: '/var/www/html/{{domain}}'
    state: directory
    owner: apache
    group: apache
      
- name: 'Httpd - Service Restarting/Enabling.'
  service:
    name: httpd
    state: restarted
